### ISSUE TITLE
「あとで見る」を追加して欲しい

### ISSUE THREAD

**Issue by eternalshining** [rei-m/HBFav_kotlin#123]
ブックマークの追加の中に、公開、Twitterに投稿と並べて、「あとで見る」トグルを追加して欲しい

**Comment by rei-m** [comment]
実装する方向で検討させていただきます！

**Comment by rei-m** [comment]
バージョン1.2.0 で対応しましたのでクローズします。

**Comment by eternalshining** [comment]
対応ありがとうございます！活用させて頂きます。

**Comment by rei-m** [comment]
仕様的には「あとで読む」タグをつけているだけなのでアプリでチェックしてPCで詳しく見るというような使い方も出来ます。ご活用ください！よかったらレビューをつけていただけると幸いです。

**Comment by eternalshining** [comment]
はい！期待通りのユーザーストーリーです。レビューも記載させて頂きました。
