### ISSUE TITLE
一部サイトでMobile向けのUIに切り替わらない

### ISSUE THREAD

**Issue by eternalshining** [rei-m/HBFav_kotlin#124]
例えば、http://thebridge.jp へアクセスするとMobile向けのUIに切り替わらず、かつWebView内で横スクロール出来ないとので、閲覧出来ない。

**Comment by rei-m** [comment]
報告ありがとうございます！調査します。

**Comment by rei-m** [comment]
バージョン1.2.0 で対応しましたのでクローズします。修正されていない場合はコメントください。

**Comment by eternalshining** [comment]
気付いていたBookmarkについては、修正確認出来ました。ありがとうございます。
