### ISSUE TITLE
新着エントリー 画面にカテゴリ選択のボタンが表示されない

### ISSUE THREAD

**Issue by masanori840816** [rei-m/HBFav_kotlin#157]
### 環境
- App ver: 1.2.2
- Device: Nexus5X(Android6.0.1)、Nexus7(Android5.1.1)
### Issue

新着エントリー 画面右上にカテゴリ選択の「︙」ボタンが表示されず、「総合」だけが見られる状態となっています。
Portraitモード、Landscapeモードの両方で再現します。

なお、人気エントリー 画面では問題なくボタンが表示されます。

**Comment by rei-m** [comment]
ご連絡ありがとうございます。確認します！

**Comment by masanori840816** [comment]
迅速なご対応、ありがとうございます。
Nexus5X、Nexus7ともに問題なくボタンが表示されていることが確認できました。
IssueはCloseいたします。

**Comment by rei-m** [comment]
ご確認ありがとうございます。Fix版はStoreに申請したので良きタイミングで更新していただければと思います。また何かありましたらご連絡ください。

**Comment by masanori840816** [comment]
ありがとうございます。
storeからインストールしたバージョン1.2.3で、問題なくボタンが表示されているのを確認しました。
