### ISSUE TITLE
時差があるとタイムスタンプ表示が壊れる

### ISSUE THREAD

**Issue by Watson1978** [rei-m/HBFav_kotlin#79]
タイトルの通りなのですが、タイムスタンプがマイナス表示されたりするようです。

https://twitter.com/watson1978/status/682538993775329281

**Comment by rei-m** [comment]
ありがとうございます。対応します！

**Comment by rei-m** [comment]
v1.1.0で取り込んだのでCloseします。

**Comment by Watson1978** [comment]
早速対応くださり、ありがとうございます！

**Comment by Watson1978** [comment]
v1.1.0 にアップデートしてみたのですが、タイムゾーンを手動で変更するとまだマイナス表示されるのですが、
何か設定が必要だったりするのでしょうか？

**Comment by rei-m** [comment]
お手数おかけします。。。確認するのでとりあえずisuueは開いておきます。

**Comment by rei-m** [comment]
再修正してv1.1.1をfix版としてリリース申請しました！手元の実機では手動でタイムゾーンを更新して表示されるのを確認しましたが、お手数ですがアプリを更新後、確認をお願いします。

**Comment by Watson1978** [comment]
v1.1.1 で解決したのを確認いたしました。ありがとうございます。
